### ISSUE TITLE
I can't move my figure's legs

### ISSUE THREAD

**Issue by AtonalShift** [BlenderBricks/EpicFigRig#3]
I parented the leg bones to the leg, but It still won't move

**Comment by BlenderBricks** [comment]
Make sure that you used the auto rig. The legs are moved by default by the bones underneath of it. But in the panel you can turn off the legIK so you can rotate the leg bone to move them instead.

**Comment by AgentExtreme** [comment]
When I try to move my left leg of my minifig it doesn't move the mesh, only the bone. But when I move the right leg bone, it does the mesh of both legs and it seems the left leg is parented to the bone of the right leg, can you help me please?
