### ISSUE TITLE
Rig Selected Minifigue returns error.

### ISSUE THREAD

**Issue by Logabe** [BlenderBricks/EpicFigRig#4]
Hi there!
I just downloaded this rig and loved the way it looked but when I went to rig a minifigure I made in Mecabricks, I got the error message `Python: Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\EpicFigRig-master\__init__.py", line 348, in execute
    if "3814" in y.data.name:
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

` I'm using Blender version 2.92.0 with nothing that would be likely to break this rig, so I'm just wondering wether this was an issue on my end or an issue with the Add-On.

Thanks in advance,
Logan .B

**Comment by DanieJota5** [comment]
It's true, the same thing is happening to me and I don't know what to do, I just have to wait for a solution, I would appreciate if you could tell us a solution as soon as possible.
Thanks

**Comment by mistamoko** [comment]
I am also having this issue!

**Comment by BlenderBricks** [comment]
This is a known issue, it can be solved by deleting the empty that the parts are parented to.

**Comment by foxsilver77** [comment]
> Este é um problema conhecido e pode ser resolvido excluindo o vazio ao qual as partes são parentadas.

Poderia por gentileza ser mais específico? Estou iniciando nessa área e ainda tenho dificuldades com o dialeto. O que seria exatamente "excluir o vazio"? Seria alterar o nome do arquivo? Alterar o arquivo mecabricks importado???

**Comment by Logabe** [comment]
Para resolver este problema, pode eliminar o Empty ao qual as suas peças estão associadas. Isso ajuda?

(Esta mensagem foi traduzida usando DeepL)
